namespace BlogApplication.Migrations.BlogDbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<BlogApplication.Models.BlogDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            MigrationsDirectory = @"Migrations\BlogDbContext";
        }

        protected override void Seed(BlogApplication.Models.BlogDbContext context)
        {
            context.Categories.AddOrUpdate(new Models.Category { Id = "cat1", Name = "Arts", UrlSeo = "arts", Description = "about Arts" });
            context.Categories.AddOrUpdate(new Models.Category { Id = "cat2", Name = "Games", UrlSeo = "games", Description = "about Games" });
            context.Categories.AddOrUpdate(new Models.Category { Id = "cat3", Name = "Phones", UrlSeo = "phones", Description = "about Phones" });
            context.Categories.AddOrUpdate(new Models.Category { Id = "cat4", Name = "Science", UrlSeo = "science", Description = "about Science" });
            context.Categories.AddOrUpdate(new Models.Category { Id = "cat5", Name = "Movie", UrlSeo = "movie", Description = "about Movie" });

            context.Posts.AddOrUpdate(new Models.Post { Id = "1", Title = "Lorem", Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec dolor metus. Nullam risus nisi, posuere eget consequat ac, lacinia ac arcu. Nulla facilisi. Nunc nec tristique sem, eu pulvinar augue. Morbi at risus eget tortor pharetra cursus eu at ligula. Mauris eu commodo nisl, ac lobortis lectus. Ut rhoncus rutrum elit sed fringilla. Etiam in accumsan purus. Maecenas orci diam, consequat a tellus at, pellentesque ullamcorper elit. Sed quis consequat turpis. Proin lacinia est sit amet felis imperdiet, sit amet convallis nulla imperdiet. Nunc sit amet justo sapien. Nulla pulvinar mi quis dapibus commodo.", ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec dolor metus. Nullam risus nisi, posuere eget consequat ac, lacinia ac arcu. Nulla facilisi. Nunc nec tristique sem, eu pulvinar augue. Morbi at risus eget tortor pharetra cursus eu at ligula.", PostedOn = DateTime.Now, Meta = "Lorem", UrlSeo = "Lorem", Published = true });
            context.Posts.AddOrUpdate(new Models.Post { Id = "2", Title = "Duis", Body = "Duis sed bibendum risus, nec porta velit. Proin commodo lectus ut nibh blandit tincidunt ut non nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean pretium, felis eget sollicitudin pharetra, arcu ante commodo eros, ut mattis lacus neque sed augue. Fusce laoreet libero eros, sit amet iaculis mauris tempor sit amet. Donec sollicitudin bibendum sem. Nullam a ligula placerat velit rutrum finibus. Vivamus dapibus diam vel nisi pellentesque, et iaculis tellus commodo. Donec efficitur sapien eget arcu cursus bibendum. Morbi risus risus, pellentesque ac sem a, tempor tristique elit.", ShortDescription = "Duis sed bibendum risus, nec porta velit. Proin commodo lectus ut nibh blandit tincidunt ut non nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", PostedOn = DateTime.Now, Meta = "Duis", UrlSeo = "Duis", Published = true });
            context.Posts.AddOrUpdate(new Models.Post { Id = "3", Title = "Nulla", Body = "Nulla mattis mi in elementum elementum. Aliquam dictum quam id nibh fermentum maximus. Curabitur facilisis neque eget lorem scelerisque vestibulum. Sed et pulvinar turpis, eu convallis urna. Vivamus consectetur vel lorem ut dictum. Aliquam ac ante eu tortor pharetra efficitur. Fusce mattis lacinia arcu, vel dignissim leo fermentum ac. Donec tincidunt pellentesque tristique. Pellentesque porta faucibus scelerisque. Ut ante mi, iaculis eleifend augue vel, fringilla sodales felis. Pellentesque vehicula metus sapien, eget sagittis augue eleifend ut. Ut sit amet nulla est. Sed vel turpis quis dui lobortis accumsan a a mi. Donec nec sagittis urna.", ShortDescription = "Nulla mattis mi in elementum elementum. Aliquam dictum quam id nibh fermentum maximus. Curabitur facilisis neque eget lorem scelerisque vestibulum.", PostedOn = DateTime.Now, Meta = "Nulla", UrlSeo = "Nulla", Published = true });

            context.Posts.AddOrUpdate(new Models.Post { Id = "4", Title = "Captain America: Civil War Screenwriters on Making Room for Spider-Man", Body = "<p>In a few days, audiences will greet the new Spider-Man (Tom Holland). A few years ago another reboot of the character didn&rsquo;t sound particularly appealing, especially after The Amazing Spider-Man 2, but when Marvel and Sony joined forces to get the character back on track, things started looking up for the teenage hero. After seeing Spidey in action during Captain America: Civil War, now another Spider-Man reboot doesn&rsquo;t sound half-bad.</p><p>When we spoke with Captain America: Civil War screenwriters, Christopher Markus and Stephen McFeely, they discussed the experience of waiting to hear if Spider-Man would have a role in the film, and how that impacted their work. Read what they said about the new Spider-Man below.</p><p><br />This Spider-Man is a bit younger, much funnier, and slightly nerdier than the last time we saw the character. His role in the film isn&rsquo;t shoehorned in, either. The inclusion of Spider-Man doesn&rsquo;t disrupt the pace of Captain America: Civil War or come across as nothing more than a narrative tangent to tease future films, which is something Marvel keeps improving on.</p><p>Fitting Spider-Man into the story, however, took plenty of work. During the back-and-forth between Marvel and Sony, Markus and McFeely were working on drafts of Civil War that included the character, before a deal was even signed. When negotiations weren&rsquo;t going smoothly, they&rsquo;d have to rework the script and remove Spider-Man.</p><p>Here&rsquo;s Markus and McFeely told us about writing the new Spider-Man and the collaboration between Marvel and Sony:</p>", ShortDescription = "<p>In a few days, audiences will greet the new Spider-Man (Tom Holland). A few years ago another reboot of the character didn&rsquo;t sound particularly appealing, especially after The Amazing Spider-Man 2, but when Marvel and Sony joined forces to get the character back on track, things started looking up for the teenage hero. After seeing Spidey in action during Captain America: Civil War, now another Spider-Man reboot doesn&rsquo;t sound half-bad.</p>", PostedOn = DateTime.Now, Meta = "civilwar", UrlSeo = "civilwar", Published = true });
            context.Posts.AddOrUpdate(new Models.Post { Id = "5", Title = "Samsung Galaxy S7 edge review blog: The near perfect Android phone, with one flaw", Body = "<p>When I finally jostled my way through the MWC crowd to reach the Samsung press preview lounge, it was almost deja vu for me. It felt like it was 2015 and I was peering into the Samsung Galaxy S6 at the very same stall. Yes, the Samsung Galaxy S7 series does look a lot like the S6 series that came a year before, and that is why in my hurried first impression I was not really impressed.</p><p>Now, with the phone launched in India, I have a review device and starting today, will tell you how it feels to live with the newest flagship in the market. I am using a 32GB version of the Samsung Galaxy S7 edge.</p><p>Also, the display is something to die for. Samsung makes even the most boring Android screen look a bit more interesting thanks to its crisp display technology. And this one has a 5.5-inch 2K screen which make everything look better, even your own selfie.</p><p>I have set a fingerprint scanner as one of the first steps, and am regretting it a bit now. The phone fails to recognise my thumb 9 out of ten times and I am forced to key in the PIN to get in. This is strange, because fingerprint scanners are now a very common technology, and you should be able to get it right. I think we can safely assume that an update in the works.</p>", ShortDescription = "<p>When I finally jostled my way through the MWC crowd to reach the Samsung press preview lounge, it was almost deja vu for me. It felt like it was 2015 and I was peering into the Samsung Galaxy S6 at the very same stall. Yes, the Samsung Galaxy S7 series does look a lot like the S6 series that came a year before, and that is why in my hurried first impression I was not really impressed.</p>", PostedOn = DateTime.Now, Meta = "samsung-phone", UrlSeo = "samsung-phone", Published = true });
            context.Posts.AddOrUpdate(new Models.Post { Id = "7", Title = "Sample test", Body = "sample", ShortDescription = "sample", PostedOn = DateTime.Now, Meta = "sample", UrlSeo = "sample", Published = true });
            context.Posts.AddOrUpdate(new Models.Post { Id = "7", Title = "Pokemon GO Australia Beta Leaked Footage", Body = "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dogThe quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dogThe quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog", ShortDescription = "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog", PostedOn = DateTime.Now, Meta = "pokemon", UrlSeo = "pokemon", Published = true });
            context.Posts.AddOrUpdate(new Models.Post { Id = "8", Title = "Gagosians Damien Hirst-Filled Booth at Frieze is Full of 90s Hits", Body = "<p>As the international art world converges on Randal Island for Frieze New York, two of the biggest forces in contemporary art have reunited in a major way: Larry Gagosian and after a three-year separation.</p>", ShortDescription = "<p>As the international art world converges on Randal Island for Frieze New York, two of the biggest forces in contemporary art have reunited in a major way: Larry Gagosian and after a three-year separation.</p>", PostedOn = DateTime.Now, Meta = "Nulla", UrlSeo = "Nulla", Published = true });

            context.PostCategories.AddOrUpdate(new Models.PostCategory { PostId = "8", CategoryId = "cat1" });
            context.PostCategories.AddOrUpdate(new Models.PostCategory { PostId = "6", CategoryId = "cat2" });
            context.PostCategories.AddOrUpdate(new Models.PostCategory { PostId = "5", CategoryId = "cat3" });
            context.PostCategories.AddOrUpdate(new Models.PostCategory { PostId = "4", CategoryId = "cat5" });

            context.Comments.AddOrUpdate(new Models.Comment { Id = "cmt2", PostId = "4", Body = "<p>As the international art world converges on Randal Island for Frieze New York, two of the biggest forces in contemporary art have reunited in a major way: Larry Gagosian and after a three-year s<p>something here</p>paration.</p>", DateTime = DateTime.Now, UserName = "Admin@gmail.com" });
            context.Comments.AddOrUpdate(new Models.Comment { Id = "cmt3", PostId = "4", Body = "<p>nice</p>", DateTime = DateTime.Now, UserName = "Admin@gmail.com" });
            context.Comments.AddOrUpdate(new Models.Comment { Id = "cmt4", PostId = "4", Body = "<p>Fitting Spider-Man into the story, however, took plenty of work. During the back-and-forth between Marvel and Sony, Markus and McFeely were working on drafts of Civil War that included the character, before a deal was even signed. When negotiations weren&rsquo;t going smoothly, they&rsquo;d have to rework the script and remove Spider-Man.</p>", DateTime = DateTime.Now, UserName = "Admin@gmail.com" });

            context.Replies.AddOrUpdate(new Models.Reply { Id = "rep2", PostId = "4", CommentId = "cmt3", DateTime = DateTime.Now, UserName = "Admin@gmail.com", Body = "<p>second</p>" });
            context.Replies.AddOrUpdate(new Models.Reply { Id = "rep3", PostId = "4", CommentId = "cmt3", DateTime = DateTime.Now, UserName = "Admin@gmail.com", Body = "<p>first</p>" });
            context.Replies.AddOrUpdate(new Models.Reply { Id = "rep4", PostId = "4", CommentId = "cmt3", ParentReplyId = "rep1", DateTime = DateTime.Now, UserName = "Admin@gmail.com", Body = "<p>third</p>" });
            
        }
    }
}
